# Generated by Django 5.0.2 on 2024-02-17 12:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages_known',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
