# Generated by Django 5.0.2 on 2024-02-20 19:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swip', '0002_alter_profile_languages_known'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dailystatus_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='dailystatus_media',
            field=models.FileField(blank=True, null=True, upload_to='dailystatus_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4'])]),
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profile_pics/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pictures', to='swip.profile')),
            ],
        ),
    ]
